CREATE TABLE USER(
USERID INT,
USERNAME VARCHAR(40),
PASSWORD VARCHAR(10)
);

CREATE TABLE PASSWORDS(
USERID INT,
NEW_PASSWORD VARCHAR(10),
OLD_PASSWORD VARCHAR(10) DEFAULT NULL,
TIME DATETIME
);

DELIMITER $$

CREATE TRIGGER pass_update AFTER UPDATE ON USER 
FOR EACH ROW
BEGIN 
	INSERT INTO PASSWORDS VALUES (NEW.USERID, NEW.PASSWORD, OLD.PASSWORD, NOW());
END $$

DELIMITER ;

	


